---
app:
  dev:
    blue:
      image:
        tag: 0.120.0
      commit:
        sha: ac9dd64
    green:
      image:
        tag: 0.120.0
      commit:
        sha: ac9dd64
  prod:
    blue:
      image:
        tag: 0.121.0
      commit:
        sha: ac9dd64
    green:
      image:
        tag: 0.121.0
      commit:
        sha: ac9dd64
