apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: appset-dev-core
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - matrix:
        generators:
          - clusters:
              selector:
                matchExpressions:
                - key: env
                  operator: In
                  values:
                  - dev
                # - key: color
                #   operator: In
                #   values:
                #   - green
          - list:
              elements:
              - appName: external-secrets
                namespace: kube-infra-vault
                # extraValueFiles:
                #   - values-{{.metadata.labels.env}}.yaml
                #   - values-{{.metadata.labels.env}}-{{.metadata.labels.color}}.yaml

              - appName: bla-bla
                namespace: bla-bla

          # - git:
          #     repoURL: https://github.com/andrey-parkhomets/argotest.git
          #     revision: HEAD
          #     files:
          #       - path: k8s-charts/{{appName}}/application-parameters.yaml # Dynamic path per application

  ignoreApplicationDifferences:
  - jsonPointers:
    - /spec/syncPolicy
  strategy:
    type: RollingSync
    rollingSync:
      steps:
        - matchExpressions:
            - key: appName
              operator: In
              values:
                - external-secrets
                - bla-bla
          maxUpdate: 1
        - matchExpressions:
            - key: appName
              operator: In
              values:
                - new-new
          maxUpdate: 1


  # templatePatch: |
  #   spec:
  #     source:
  #       helm:
  #         valueFiles:
  #           - values.yaml
  #           {{- range .extraValueFiles }}
  #           - {{ . }}
  #           {{- end }}


  template:
    metadata:
      finalizers: []
      name: '{{.appName}}-{{.metadata.labels.env}}-{{.metadata.labels.color}}'
      labels:
        appName: '{{.appName}}'
        site: '{{.metadata.labels.site}}'
        env: '{{.metadata.labels.env}}'
        color: '{{.metadata.labels.color}}'
      annotations:
        team: '{{.metadata.annotations.team}}' # Use team annotation
    spec:
      project: project-dev-clusters
      source:
        repoURL: https://github.com/andrey-parkhomets/argotest.git
        targetRevision: HEAD
        path: "cluster/k8s-charts/{{.appName}}"
        helm:
          parameters:
            # - name: app.image.tag
            #   value: {{.Values.app.dev.green.image.tag | quote}}
            #   forceString: true
            # - name: app.commit.sha
            #   value: {{ .Values.app.dev.green.commit.sha | quote}}
            #   forceString: true
            - name: app.color
              value: "{{.metadata.labels.color}}" #color
              forceString: true
            - name: app.env
              value: "{{.metadata.labels.env}}" #env
              forceString: true
        #   releaseName: '{{.appName}}'
          valueFiles:
            - "values.yaml"
            - "values-{{.metadata.labels.env}}.yaml"
            - "values-{{.metadata.labels.env}}-{{.metadata.labels.color}}.yaml"
      destination:
        name: '{{.name}}'
        namespace: '{{.namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: true
        syncOptions:
        - Retry=true
        - ApplyOutOfSyncOnly=true
        - FailOnSharedResource=true
        # - PrunePropagationPolicy=orphan
        retry:
          limit: 5 # Maximum number of retries
          backoff:
            duration: 5s # Initial retry interval
            factor: 2 # Multiplication factor for the backoff
            maxDuration: 1m # Maximum retry interval
  syncPolicy:
    # Prevents ApplicationSet controller from modifying or deleting Applications
    # applicationsSync: create-only

    # Prevents ApplicationSet controller from deleting Applications. Update is allowed
    applicationsSync: create-update

    # Prevents ApplicationSet controller from modifying Applications. Delete is allowed.
    # applicationsSync: create-delete
