apiVersion: v1
kind: Secret
metadata:
  name: dev-0001
  labels:
    argocd.argoproj.io/secret-type: cluster
    env: dev
    site: wdc
    color: green
  annotations:
    team: dream-team@example.com
type: Opaque
stringData:
  name: dev-0001  # Human-readable name for the cluster
  server: https://dev-cluster1.apik8s.example.com    # API server URL for in-cluster
