apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: root
  namespace: argocd

spec:
  clusterResourceWhitelist:
  - group: 'argoproj.io'
    kind: 'Application'
  - group: 'argoproj.io'
    kind: 'AppProject'
  destinations:
  - namespace: '*'
    server: https://kubernetes.default.svc
  sourceRepos:
  - '*'
