apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: root
  namespace: argocd

spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: '*'
    server: https://kubernetes.default.svc
  sourceRepos:
  - 'https://github.com/andrey-parkhomets/argotest.git'
  - 'https://azure.github.io/secrets-store-csi-driver-provider-azure/charts'
