apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-argocd-applications
  namespace: argocd
  labels:
    argocd.argoproj.io/instance: argocd

spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: root
  source:
    directory:
      recurse: true
    path: cluster/argocd-applications
    repoURL: "https://github.com/andrey-parkhomets/argotest.git"
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
