apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-argocd-app
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: argo-only
  source:
    directory:
      recurse: true
    path: cluster/root-argocd-app
    repoURL: "https://github.com/andrey-parkhomets/argotest.git"
    targetRevision: HEAD
  syncPolicy:
    # automated:
    #   prune: true
    #   selfHeal: true
    #   allowEmpty: true
    # syncOptions:
    # - Retry=false
    # - ApplyOutOfSyncOnly=true
    # - FailOnSharedResource=true
    # - PrunePropagationPolicy=orphan
    # retry:
    #   limit: 5 # Maximum number of retries
    #   backoff:
    #     duration: 5s # Initial retry interval
    #     factor: 2 # Multiplication factor for the backoff
    #     maxDuration: 1m # Maximum retry interval