apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

helmGlobals:
  chartHome: helm-charts

helmCharts:
- name: my-argocd-secrets
  releaseName: argocd
  valuesFile: values.yaml

- name: argo-cd
  repo: https://argoproj.github.io/argo-helm
  version: 6.7.18
  releaseName: argocd
  valuesFile: values.yaml


# resources:
# - overlays/AppProject_root.yaml
# - overlays/Application_argocd.yaml