apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

sortOptions:
  order: fifo

helmGlobals:
  chartHome: helm-charts

helmCharts:
- name: sealed-secrets
  namespace: sealed-secrets
  repo:  https://bitnami-labs.github.io/sealed-secrets
  version: 2.16.1
  releaseName: sealed-secrets
  # valuesFile: values_sealed-secrets.yaml
  includeCRDs: true
  valuesInline:
    fullnameOverride: sealed-secrets
    namespace: sealed-secrets

- name: my-argocd-secrets
  namespace: argocd
  releaseName: argocd
  valuesFile: values_my-argocd-secrets.yaml

- name: argo-cd
  namespace: argocd
  repo: https://argoproj.github.io/argo-helm
  version: 7.3.11
  releaseName: argocd
  valuesFile: values.yaml
  includeCRDs: true


resources:
- namespace.yaml
- overlays/AppProject_root.yaml
- overlays/Application_argocd.yaml

# patchesStrategicMerge:
# - |-
#   apiVersion: v1
#   kind: ConfigMap
#   metadata:
#     name: argocd-cm
