apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# sortOptions:
#   order: fifo

helmGlobals:
  chartHome: helm-charts

helmCharts:
# - name: sealed-secrets
#   namespace: sealed-secrets
#   repo:  https://bitnami-labs.github.io/sealed-secrets
#   version: 2.16.1
#   releaseName: sealed-secrets
#   # valuesFile: values_sealed-secrets.yaml
#   includeCRDs: true
#   valuesInline:
#     fullnameOverride: sealed-secrets
#     namespace: sealed-secrets
#     commonLabels: 
#       app: sealed-secrets

- name: my-argocd-secrets
  namespace: argocd
  releaseName: argocd
  valuesFile: values_my-argocd-secrets.yaml

- name: argo-cd
  namespace: argocd
  repo: https://argoproj.github.io/argo-helm
  version: 7.4.7
  releaseName: argocd
  valuesInline:
    crds:
      install: true
  valuesFile: values.yaml
  


resources:
- namespace.yaml
# - "https://github.com/argoproj/argo-cd/manifests/crds?ref=v2.11.7"
- overlays/AppProject_root.yaml
# - overlays/Application_argocd.yaml
- overlays/root-argocd-applications.yaml
#- overlays/Application_csi.yaml

# patchesStrategicMerge:
# - |-
#   apiVersion: v1
#   kind: ConfigMap
#   metadata:
#     name: argocd-cm
