apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# sortOptions:
#   order: fifo

helmGlobals:
  chartHome: helm-charts

helmCharts:

- name: my-argocd-secrets
  namespace: argocd
  releaseName: argocd
  valuesFile: values_my-argocd-secrets.yaml

- name: argo-cd
  namespace: argocd
  repo: https://argoproj.github.io/argo-helm
  version: 7.7.3
  releaseName: argocd
  valuesFile: values.yaml

resources:
- namespace.yaml
- overlays/argo-only.yaml
- overlays/root-argocd-app.yaml

# patchesStrategicMerge:
# - |-
#   apiVersion: v1
#   kind: ConfigMap
#   metadata:
#     name: argocd-cm
