apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

helmGlobals:
  chartHome: helm-charts

helmCharts:
- name: sealed-secrets
  repo:  https://bitnami-labs.github.io/sealed-secrets
  releaseName: sealed-secrets
  valuesFile: values_sealed-secrets.yaml

- name: my-argocd-secrets
  releaseName: argocd
  valuesFile: values_my-argocd-secrets.yaml

- name: argo-cd
  repo: https://argoproj.github.io/argo-helm
  version: 6.9.3
  releaseName: argocd
  valuesFile: values.yaml


resources:
- overlays/AppProject_root.yaml
- overlays/Application_argocd.yaml

# patchesStrategicMerge:
# - |-
#   apiVersion: v1
#   kind: ConfigMap
#   metadata:
#     name: argocd-cm
