---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-oidc-secret
  labels:
    argocd.argoproj.io/instance: argocd
spec:
  encryptedData:
    "oidc.auth0.clientId": "AgDpc5criSF/LgqAZb3tXnsw6nWdQt0yPghQe81mn+5Kub8cCAVPtRA70dex4he8lBIdqImwEKQ/H4eD+lIgNTyKjYr9gUYmCY9916u0QSrIuOqDy4sbD73ovbeLszFV52zfjtAK7fFWRd7TVvOKpXV87SW2C47MOiUTPMBxLS96uWGxnnT0TDvEXe8XkhJtvBPiXYCnzPpyxoNh09vzyZEj4YX73vaIHzVTT2DSJiOjYE6u5CIFgPX+yiUoIuLj5/xj6dH5mKqYktaJKS/6Chh+ngUzafLQMbkuE90uLwer6vNPn1RkW8mP7F3NxSBvXQU86kg86X/NCYfxPGbH/Qw3Urj1wcZJ6T6Qi3y1E2LFy/wEWm9x1VvqkuvL7AAdFUvfHT3CASvCQzbPT/Qo3hBpdD2ZOR6gTVLsWWznhnuX16EVUdBpDtGvwr6SBSsc/2l74O1yXVZDTKeZuHhmD+aGL7CstkkS20s+doKynr7z0E7VH3HHwn3pfAt3lvNOJI5kqDS6vWxP/H54hahd1O4O6rA3JiyD0WYuZUmx1V+BbSenZEb3MOeaPjYaV+2n+VnmzpmUDfWwarJ5pDoh2bqiO8iqJIbvKsrYbZ5NZ7c8x+mzIyNdvWJZcYTgWw9sfVBmfCm9N22fqZAKTgcxXwXVdSmYr+CAgJIWz+NgOHs45p0ADHFWZ1+U9jplyIM77GRnxUKAc2VzrpR0qjLiyD9QzvhJ1A=="
    "oidc.auth0.clientSecret": "AgC2/38/K+9AIpUJf4Se7lYdkVuMkBGjulO1+QIwwKg5tukUOX3jTwrqEv/wZoc4mhGVwpBKO/sqeUyt4Hk6sngdyRrufg6qMEh/nw2z+92IocDMk36hj3XxKbeAOv/9bVnDdd0kOOPhV6B93nhxLrGGeuop8JrRDEQ6jsIwVsYH77XVlFRLCOwaQ9G4m5VvyZXubtbji4p08N7PQDBPEfAsv8TZU3LH3W7T6F0JTNMwX53kx2ItID5iaYTo3+flUmTnkPrpnHSit6r75oymivUIAuRt/DLypSxXKjxZPi71pfiiFR+U9KRAuMml4rlf5kF/gJhNiPWDImlGtRNlxPeSvas2FjPIddljj8dq8mAC/DK48U9MLDEADNHPHbk5hNTtKEAOszH+orEgEUp4Wd0Rj22cGN/WAxBl0Px9pVOFlTQ7Tcxks5AbCFP42+oyBLErMyRi1uGc9tHYqiuCigUv3wnJqfb/yleaMyEdjhgJg5Du97Z/8pMivok9AO7MRfO1rIce+LHZoHm0hvliMaHD508l8F3N0eX+NccRjMWVjFcyj6/0Svzuh3kMWPXwL6VMFr6391UhqGG7FB7ZwYebvt71f3kCCWZqiWGcrzDEhV9DxKav4A6ZasEEnqdUeRl0NzPLh5R96N76vpCe5Y0o9XsnxvWpI7Sf8CRMsX6E3TuZuxu6HA+NBIKnOmZ2pjSNDu7Fhn9u0mNJJbnSnD4g7Msz3deD+2WgcrJdT4nqEyODUC5/J53n"
  template:
    metadata:
      name: argocd-oidc-secret
      labels:
        app.kubernetes.io/part-of: argocd
