---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-oidc-secret
  labels:
    argocd.argoproj.io/instance: argocd
spec:
  encryptedData:
    "oidc.auth0.clientId": "AgCo1zRqhyiA47++kf2LuGaLXtjSY1lAaGVjGmRE6M+SMJ37g2QctaM9RLbZ/ark1p5YOT7V+XMRsFqLaHI0Z5917WaCB2mpvqBy5iIEFuWSBDshkKdarOTcx/JIYg/WX0zzh8Uog2Zpc1oHnom8fvUrSPC7D6HaQue4qYbXl+AUhYdl5Zl6UrgN9uUp0Ho14tQ2yYcc5Tvh3Xqf6sztv1eYc6Ey9IYFtugc8pthZVgvYQSTSoaepqVVW6weGv3YV1gt+9DBwAYsgPcHdFfADHzl7AgSp9UGyY9JRTVqewQ/k94hhLUZ+e4xc74HhdxMS5BBwY4g5enWJOSrGnBbyecpLQW2iPwrnIs3bkL858j4+ZyCQ229vhuhxEM9ixvZpmh+KqccoBdQVjEPFXPiWkh5cWJmc+od8Se+nrkFwJSOcoeDGqBowKDIbPwK9+Iscaw/Ei+8r5H87ooA3dPMBlIKuLw+WYRTYukqtw5dqGcIXd51CTu5M4MfH7RXMb2WhL3R8/55jgqrOBuNQdtlF9ftLQQxxHebCpQ1p2sbpwvRJTbf4230BSPxdsI5kkooU2UqZXNNI14lCwQ2PSjCGvf5iyjfb41AoCACT04Lyi0g9zTAZi6Z0CXt2q+RLp0ZVUxiLj5d/aHraVm0oGeyIPJVrK+UO9RsPoJGho11KSpU69hEcIS/68MYmz6NBX+cJ9QcM79EDFurqdgLMdFuBINiOzNhvw=="
    "oidc.auth0.clientSecret": "AgDdZm9J7fUmHSJVTFm4S0aZYSLE+m01BsRus7l7sloylbYj4hkX4QVFL/PaD/fmZsRG0YF6lPKAgmkYpI5pru+zL+/uwce+W/5ZDPnlEe4RunH5qzENV8NWrndZwMThzkZiVQvobrVfcAByTwQ9HLgUtTO/iESlkR7bPYw1oehWtgfQt2s46ThAhlnSfICNmMZ1kOY0fGznumasfw1mBOaZFTWZ6KpJs0Dqef+PiTBkJVkgV2I9hqqa4yMpWnafgX02qL+kYNixLJVrwZEidAZXkeDUbjpsbz9RORZsXAyPcz24guToYekECadb1ID9bRau+tzfzug6mvyTDfBAF+qQI2Q4trXSJfFHc19lo/g6lbiaf97Z4SWjoBhjLLNtpaLY/z3Rc118M6EpSuZpz2UiGSShaEXZiKcRVcKI4Gvh5rl4T4ur8BPGVWnKP6bDa3/xDYCUEq1qWXb/FRT9ZbBkkwyx5e3Dr5bW07epWS+O8XPRRXCEWVXu82HT25Mai6j8UA7C+q/zAPvXX5w7aGXKe6OoBHUXDHy6Skx8WthxxFtW5FFlFMTXmDN3H3y5H0h6FHLblfQBNpgSc63fY1+ub81N5FPCantV5PvAyEhznLYTk0mY8kuTACyDtCkTDo8nqfpax0ZUSd6kQmElEyGVhsGXx/W0AeHDw0PsiKwjnM+HluPtu/OyOmhVj7WWl3Obu45ICYa1cyga9Cw0C5diHRNqdwpVdWorziZIQZHMg5i8OGws7+Pu"
  template:
    metadata:
      name: argocd-oidc-secret
      labels:
        app.kubernetes.io/part-of: argocd
