---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-oidc-secret
  labels:
    argocd.argoproj.io/instance: argocd
spec:
  encryptedData:
    "oidc.auth0.clientId": "AgDC5TmcRJECso1o19refXKfXE2PtvJIslXSEKu7cdtDOM1BRu7OkvpCFCW0pFYSXVIAU3J/1lXWZcdLh3m4nl6sX3Trdv+Vo+P7BbgWYa9Ng+TSs57lCjfV/sws8xcdbtDnz+mZ1uAu2fk7hWgCvJEf40dm3cCl7lkllvpk//9NI6gGm7LNqldl8AlkEGPa42flaeMQH/C1zukVyDso2Imilc3AbLYrg4Me9DQmzkJyrHBneYS6PDxh4Qjj5TW/8N5Tt1TJYAPtH2EVUpwbVodpEojV4CZ43+8Et8yGn5NYWutybgKeWEe4EiYLQaqb22p/4Rp9Y8WcSJOgiMKMw18sPkSbDyWqeSfoW/bWfQ/ONAxxdoP1/O2cnarwM2961/dW5vgLlYdrmaE5Ebh34B7r7x5JZzDz7AlR/1EltQm8L/J+SKLvMN630eX4gWNRbB3QY0uxJXJl2nWoCZML2Vc+I4I8S0/hGghooVqq8mFVIrmJa4E4EU5Of1oH9wTt3g0mW44zWNfMbhW+/xjSy1NQnwg/6Q6/vj7OMtJQnXGM18zkWlRHDfFGjdfsxTELrc4BWoJr526SArBuprSbX2gudZrXV+xefavc/k1SvID+ZfKhUnoCdDN32lDngS1l82H5YdlrMdB8e9QfU122RJnvPcZx+mXHfJe/EAyZMEUQdZn82JaniIYtaSjiMCdQdUqc6TE3OCxwmHZy3ma/20mt8kCDdg=="
    "oidc.auth0.clientSecret": "AgC1drKbb/ZOMYzhbSvxlFoHxGTTDAx8b9gYqhG/letOK9yuwdDeYgi0xi97zvE8iN2nh5jkGnpLteV8I2ue3YYa0aUXgt7/+kN9BSC5/XQC6w0BLo4QFJObzA06cgx7oI7R1v75CEW2BqJ74SHcs+tPg2EOwP3Byk3Pxxc6CB42XQo8YR21vROTYX8NR/I75jaK0nvYiFomJK0efNLFyl8ewXiZieZf1Dj9lYNdk198xTatRjA/x/CNdSHOi+N2b1XsO0AXhLM1K7x7VGdz8NxJLQ4FrYUqNq883f8FkhcHYV3POSBtpvv3xZw4ZG1dJuXhpjjhnBTGXQI69UsGXou1xsC8lD4a9IIv2y1MEq2UxTGX+peQMVLvmBEH/IndC35VJFqwyEtHS/XC0ebtxT7OLndiwyFMGRQ4nP7QjVtLRhkyR511jKgsIQaEkqEaBiG/GEdWskjAtrG0leZFyOdcFLcvrtMVY6uq4kzV3zXeZF4tTQ5JgHyU5v35qS0nf5MngE94a7ElUzfFUo5HOMoiHot7xB1ys6sMyFAYz/D9oz5S3KeZ8lx/r2nGtaMNboFN7EMPJMGrX91ZqkvkjwjT87MCYp/4p/IfKV9LygwHbtvMcmO5FBeYf+MJTKnnwbDc3oR5owe8t7VnXEzz7blR492x6sDriHUupqL5ZajSCtPA3IDXkotnmFMNGvSfIbP7qJG5RZUtn30aTEUwH/yUxOuWffIU17O/rqt+nkOwvcxREaYHnk49"
  template:
    metadata:
      name: argocd-oidc-secret
      labels:
        app.kubernetes.io/part-of: argocd
