---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-oidc-secret
  labels:
    argocd.argoproj.io/instance: argocd
spec:
  encryptedData:
    "oidc.auth0.clientId": "AgAw1Lz6ByH5buSSxqCbUr1jnyjCHZJ3tXYz+yyoBlBxPryAjPHUHw6/1jZcwWkY64MssQB33GmDzeEquo70B8aiNuPNMTTy08EJuGtl3b6KvdNC7DpmMz9Uj/tG7KI7EvaG06XaiKgjelN7ojWHSH5wz8VkVM0GKmqNa+9uJ4mCILjTdalT0164dOR/Dwxp0UKwd0HxFWMcEU9pokBFhCxgtg0suDp2uhR0xALL1RdjpfVzJ9+Iet+MbDsdxufiZKaWksrwPGJrZLNwkrdlRMARvWk0XJQAe4+bdPS12dgEc5aQXwBnhuq/ThzaWwnutFzDOTPEOJGKirlmLMJ9SY0TZDnaYrDHWyEACtVNkc/aI7oQfXgCdc6+0VzVMQhbtLJb9Cfh96hveiJDYB3SfceZysAXps+bSaLhqz4iPJI+D9hqvIGXoeRKwyaUO+O6fsEg1hXbKH3Dva9K/VLhOe+zzveUUt9kYiE/xoqSVntrjDXprf6UNIRmdcVHrxKvuNkZtcgE4Xhtr0iAMsc0Zor1gzK73RxCdguOFuiwHquKYXqOuwnac5g2yL03dYY8RK2KKsKJ0bhvTVc2benAXKhkoShBtVNdVu+7K0EpZvJ0sLFgotzfxPsLgATn+km1TNNV3rVVW17W0ea1ydYkRFCh0z7J/9YIzX9i3FQeJhIaxGKQ+olQGeepegyDGvW8tDaICWaVZHCQVPajKU3LtAcy2RG/uA=="
    "oidc.auth0.clientSecret": "AgAGuED69mo1oBw5k+U7/yOZCJMCQb2LuBTnIbDcmInSWiF7X6XCRgav+hETmd4nnxapMhlffWtTiacZcX+JSHqcDADk6DJ5tS1mOCIGInVdTQSNCq/NpPR7L2IQD9j2Yh3UCNcaZB1B+FUp0wpGqqw68PrCPfWh65p0HPGVixFHSD5/8uZnZhkk5mDwtzP5UUV7Kl1fBy4u5RWd5/tbRE9KLJTn66l1QX7ns0KeOIoK7F6rQucOkg0SA1TVdNYE2PPsCRUzxplkEcvcblvWGI21JkQoni3mgJ3KeSqJPB3nDLhJ0nuclSAmuZjh4121OrDBRpj0kvV+z+IVwEBXPDHTLi2mseB3vQp4vrgmgtiFwWG4Yo/GVfAbCZJ5mpwlHaZabWKUWZBGS0WT45AbXhr8EibDp6JtevroFEhYANS16vD8EfMfBNbTe60dloE0A0URW+tt0GoAkFL+ZM9R7zFK0wcBWckTWas1NHyMANeGoY8bBQCzT5EI/Di3FX6yw3OUClNasCE/0Y5cEKqXBf5Hxew16t1NWDhLs7wlqhvy/IHPlRNrU06w5HxN7AaAeZw3e0ldf4tVkJ+4N36mSm9ngC7qBgVowGMQUnfK+NZrGBVi9xjqnY8h6I9OK+hartQazQjO8HE3br9h8LTQqL61L/n7CiAYDm1NQifpTq2iXoqarAy0uPvE1XhpHYSI2Yqz5dg54FHTx25y9s1CbFdY+ra3rrQzMug9tCnFmVtE2ygYX89C8+2p"
  template:
    metadata:
      name: argocd-oidc-secret
      labels:
        app.kubernetes.io/part-of: argocd
