---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-oidc-secret
  labels:
    argocd.argoproj.io/instance: argocd
spec:
  encryptedData:
    "oidc.auth0.clientId": "AgDpc5criSF/LgqAZb3tXnsw6nWdQt0yPghQe81mn+5Kub8cCAVPtRA70dex4he8lBIdqImwEKQ/H4eD+lIgNTyKjYr9gUYmCY9916u0QSrIuOqDy4sbD73ovbeLszFV52zfjtAK7fFWRd7TVvOKpXV87SW2C47MOiUTPMBxLS96uWGxnnT0TDvEXe8XkhJtvBPiXYCnzPpyxoNh09vzyZEj4YX73vaIHzVTT2DSJiOjYE6u5CIFgPX+yiUoIuLj5/xj6dH5mKqYktaJKS/6Chh+ngUzafLQMbkuE90uLwer6vNPn1RkW8mP7F3NxSBvXQU86kg86X/NCYfxPGbH/Qw3Urj1wcZJ6T6Qi3y1E2LFy/wEWm9x1VvqkuvL7AAdFUvfHT3CASvCQzbPT/Qo3hBpdD2ZOR6gTVLsWWznhnuX16EVUdBpDtGvwr6SBSsc/2l74O1yXVZDTKeZuHhmD+aGL7CstkkS20s+doKynr7z0E7VH3HHwn3pfAt3lvNOJI5kqDS6vWxP/H54hahd1O4O6rA3JiyD0WYuZUmx1V+BbSenZEb3MOeaPjYaV+2n+VnmzpmUDfWwarJ5pDoh2bqiO8iqJIbvKsrYbZ5NZ7c8x+mzIyNdvWJZcYTgWw9sfVBmfCm9N22fqZAKTgcxXwXVdSmYr+CAgJIWz+NgOHs45p0ADHFWZ1+U9jplyIM77GRnxUKAc2VzrpR0qjLiyD9QzvhJ1A=="
    "oidc.auth0.clientSecret": "AgBnktXBdL4NemeOgMD3M7FEm4pgLllcip2WEbSm0R3va53rosQJ36RKO4XUJJFNwBpXqOjX6XVK2t6nwxpD9A0PQgAKzwlG/49qaWm66wu0TOx+mDlRNCALN1PYbQg/jP+hKrdOLp4L/KuU6B5AWGSdFjo2KMint/t6pfx0oMi7arNB6sW84iX9MRcgwO1bXgMBpN6abw34ZcXvWatxFbpyPUxmc0OoTBSB+GCIzHPQBZG0A+djgCUBQgzTe9JJWZO8Dk+XPc3e9ft0Si2gMUivFtBAAFjnPEcnqpOJizmRT1ypbV5saUIBQB37ksQb/YfweCxJ4eWQX6ieE7eVCyyGZ0HQD6enDe6GOb+Nhod4t9PZie2ls4vPFJH3bdzgvBmKgkKJivWUnwfJ0zpTz6JlDUA5oa2TKI7zj+/koiaqcdzdUNjkmxONE1nb1eRoDxi3qpzMPYR88jHOm902+OmLtHcNZUaEaUVTo2KxPwCMessnSibf3pMqBI0XPJ3acgAmQ7CILNPwAn+BpPjAFWV0ZAGxVyK1yN55daQ0MWFLNAoP5b0QL3btdCAzbg98o7W0UK/QsXlGkJHWVnlvSDuavKNsBz9JB/S0lvUhMpbQ8hIlN2Z7P7FDsRxTnhzs6bgpZm7tnUZCwmmf0NBgY+j+RDzqd46fD+7hJuaJ3BXTs/INxXcm7JHbfssLQ84x1iRn9sMlS3gDXsc0BSdxw5aRQOY7TjyjL9gWDeT2NV4RQn+c+hlRteXM"
  template:
    metadata:
      name: argocd-oidc-secret
      labels:
        app.kubernetes.io/part-of: argocd
