---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-oidc-secret
  labels:
    argocd.argoproj.io/instance: argocd
spec:
  encryptedData:
    "oidc.auth0.clientId": "AgCRxw6Y8AQDJjlXnPDP1Tc7seBAVUh5uPtPUvz4vZ1dDMSrQufkydaQcqPX5lE67HaCKFSBhpu6qLJSD+m6BnYPtqhZWPYpoZS1IEPHjg4aqrx/N7Tw2YbRu5lkOGLanO+um3dOYVsEuwcdMZ0/5WnbUmRZ1Cnz6TIiBHRROfjkOkUxDNP6nCfihCqdxR0YxBM8gEEcM7KH3lc9yqFZpL6umF08rYwLRfFNmO9LBAbZb9X+jdbL1068uej2g6Z733PvohHBKOB29vmUSWJeypXzWpuc4wbfFmKAK/cTkkbo9csDCHIeIT4l+Uhrqm2XL5V3Wp7j6d5pH8YpwUs3JfmxxvDUci3aisbJxLhvIYPkS/V6Vobai8B2/czRQxaaOCixU6q/ll5RzXZq6sqcbJyxOfQ3QxjCW34dMOOZUVDwqZ1DXjHQPFoXu4HBvs5fXJw8YbCkpdflUeYar2oGjhzKAu0B368t7pM3aZ2tb4On9XpXMuYIwH0A6/Y72WDfE+mFA19Ly47AyMKwSpYZMWVKlGNtonXH+JISkWCSf4C/cJd/MYOLqiC9OtZHVrLuB6BScHOHFFFTHIexSn8/5lFTc8XskeMN6XfXbqSGs9L6iTBOTg5m5ridH8xa9Z4PvA5h6xYmNZ91W8cyLQh59l23kuP9r7+4wEN08GWdMpYl5JTk40bP3GZpzYnB64W8flSj79h3ToFcS5wi0GAebuXF4ZxYww=="
    "oidc.auth0.clientSecret": "AgBMyMAxhJK0opNCunPePFXeYUpShpvF9KwHWMCZE7KLyVpXIJsU2US2xvDaiDQFxY7PkxFLqk67SYNhXmQTNNKSnWkRq1JMruyV93g4icYCHoYiGKNmeQAuRvkZFg8pniLv8hiPJG8Cx/oY9bDveWFTaZRhXf367YOINby6USn6S/FTVWDQ/rAa/8BIXUxsV1orAShLekjWOtwAiPgm91c5vQ8kOX09ORDJ0bVagiYQKS6orba3bWGUhGO3MwNBBRctTylmdrQUGb08QUPlF910tHeCBNzF/jbfU+4uKjZbG2eedKwRwRShilsmjK7UyRmyJBwvpLX/QMCWCMz/l0rWosq5PBBStquYDNAk90krSRV540Kp0uNfqE+SQ80NnV6NFsAVG6Y8lNVrtdCoYxlTXBx2dkCK6a3lxPmK25K4EuwQWLjwz+uFKduP80czPfXk3gGVWHLVM014jKm2WNodiHNQoHQgPWWzSvVzQaWvotIIOkiXDhIBJGZqQDnrKuE90/5oJlTGJ0N7ASdHwCkPDw/8sapHFoJ0eKnSMcXFVw0p5QHjuVuJVll3Q/Iwlg0wXoL45bpJJg2gyHYExeB51tHne5sRTZ0Gc6yoE/gKbz/I+Qdug0orALHBiQgrAgCL/Z6jnXtyZD4+p+C6/skcSh1OX+rpFjILjiYtLDaS5zZeF1n7/TW1CWH6DlFrwOAaB3wv6n7Z1ECy5pY2fvuJp3mq8Z5XmiEovzUs0m39M2XMz53bsOaz"
  template:
    metadata:
      name: argocd-oidc-secret
      labels:
        app.kubernetes.io/part-of: argocd
