#https://github.com/argoproj/argo-helm/blob/main/charts/argo-cd/values.yaml
global:
  # -- Default domain used by all components
  ## Used for ingresses, certificates, SSO, notifications, etc.
  domain: argocd.local
dex:
  enabled: true
  logLevel: "debug"
configs:
  cm:
    create: true
    kustomize.buildOptions: --enable-helm
    resource.exclusions: |
      - apiGroups:
        - "velero.io"
        kinds:
        - "Backup"
        - "Restore"
        clusters:
        - "*"
    dex.config: |
      connectors:
        # GitHub example
        - type: github
          id: github
          name: GitHub
          config:
            clientID: Ov23lipfZoVOd45eDwIs
            clientSecret: $argocd-oidc-secret:dex.github.clientSecret
            orgs:
            - name: klf2000org
  params:
    server.insecure: true
    server.rootpath: "/argocd"
    server.basehref: "/argocd"
server:
  logLevel: "debug"
  ingress:
    enabled: true
    ingressClassName: "nginx"
    https: false
    # annotations:
    #   nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    #   nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      # nginx.ingress.kubernetes.io/rewrite-target: /$1
    hostname:  argocd.local
    path: "/(.*)"
    # extraHosts: 
    #   - name: argocd.local.192.168.105.13.nip.io
    #     path: "/(.*)"
    #   - name: 192.168.105.13.nip.io
    #     path: "/(.*)"
    # extraPaths:
    #   - path: "/(.*)"
    #     pathType: Prefix
    #     backend:
    #       service:
    #         name: argo-cd-argocd-server
    #         port:
    #           name: http


oidc:
  oauth:
    encryptedClientSecret: AgA+IyYotCjFxFaoixu6aJnQ9PjULQ2a25EVwsOTgntsfRsUevcUPiaKkopUAUHV9KdgVyA0yQ2cY/CR8eWxJJRHiCtLZmA/qxnHLOb5qjWqDwbK2vNTB10fFSOShaXlaTJpzINJGHnoQth+oClHMm4v+5I5aEjLgAuCk8ro0fka7sG2z95CbtGYbI2khSn9L43ZMfdKKgzXQR2Qtxk63XlrFuUwYlzKZTn1IDO0ENis+ue+mvhs//eBT3TXeQ4dttTsx6gpnghXV1uDKGPnDYOhpSRvEMDrNCOVU9kSxyMBwn2Qr3z8CKVOF4uFs+yvbVOrDsr7lslIFmoEwJN90CrVj/4ASq6/qFq6IsRuDjTQOHM5GJJlsKgVG9C26OO4XfVrya0EFUhuxQeScPiUslIaIDVE0stObAjRNW7iHd7TAMhBCaWor7f+7nxxjOzgvP6768+w+zVb1m7n/UrSJY83GmgMGsCPWelflR7q9bM6RN3yjRjJhdNFzICSK3ghg4YDlIC4sLvvqtML7SYgd+wY/3tJeBdvUxiNyqsOHdqGemuGFRQaAVx8ROx+aECkI+aT26Tfd2xIn5mNC+RHhWg3pNvuDH7H7ARc5i3gS7w3cJE+tlchstb49Nd+KdG3kVVb2bKc+N5wm+GLVbIKVE1SVLUWCDndM82NOmaGL+rh7EqLHwa2LAct18rGGSefn7N8tD1tcCjOlXrzum9q+QZXKx4sI2VaSRE/cmzSjnJwFnOyaH0qtajO
    encryptedClientId: AgACPTQZgV9B2Rm+DmQlmv4WrnL+mKJ9doXmwLffEUoBAbWCNcD4e1r5IpxFT0DuMtEdlGddwKbuYvE1NJKcXTcwzrzjhQT8GkggyTCeZxNGtLD9nPK7FjLVxv2uU/pTNG/xcXsRY/+IXg7L46B6API5dqAgTnjlXAO9A83kf16i+hwDrG5MAuDnx7ocyj9EjhIUkwRzVxasrgO8oD3AMtfANQKByZI0rUw2Gk6e2RasbBANgHQQLU/WUIyC3HCRnqDxvxESv3JKdKN0zuWiwQhDn4yPkZ7SxEm8M3qeRKVm9+likiIZOvxVea/pWTZUIv12sLxjxnzlbZ268LwlUnO7YZlAocCEe3J0ulNY7Z7x5SxRbdL2zrSQhnL0iFx55HupEVRUnHZ64FEfnIgWSWGiEVNoJxEP3gUTF79i62Oik0Sm7ZcvZpXs9nnmBiLosg9MyyXEWDyfEccMG9+V3aUFBl8Fl/jBXANCygxPJIJfE9tbXi+dSdVuPGu3cLQh55w4o1a2B+/WeYjXK7s1aSUMl4lFa4TZQrC7XFE/tYoRrL39iIGY8CsGdfhp1JcOr+d8uqI1IbfkMPCHOd/PwyBDfrdNngdg+lDc4cPKTt3gBzsPKkcDBtK5RdQJaRxzH5fp3PGY5XxGyluWQMffMjctEXG1FRx8cu3B/RWQrT6acZzdt5HESowtqNt49Fnr6CbpPxwxBigYIk+YMs9pCTypa6KtVQ==