#https://github.com/argoproj/argo-helm/blob/main/charts/argo-cd/values.yaml
global:
  # -- Default domain used by all components
  ## Used for ingresses, certificates, SSO, notifications, etc.
  domain: argocd.local
dex:
  enabled: true
  logLevel: "debug"
configs:
  cm:
    create: true
    kustomize.buildOptions: --enable-helm
    resource.exclusions: |
      - apiGroups:
        - "velero.io"
        kinds:
        - "Backup"
        - "Restore"
        clusters:
        - "*"
    dex.config: |
      connectors:
        # GitHub example
        - type: github
          id: github
          name: GitHub
          config:
            clientID: $argocd-oidc-secret:oidc.auth0.clientId
            clientSecret: $argocd-oidc-secret:oidc.auth0.clientSecret
            orgs:
            - name: klf2000org
  params:
    server.insecure: true
    server.rootpath: "/argocd"
    server.basehref: "/argocd"
server:
  logLevel: "debug"
  ingress:
    enabled: true
    ingressClassName: "nginx"
    https: false
    # annotations:
    #   nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    #   nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      # nginx.ingress.kubernetes.io/rewrite-target: /$1
    hostname:  argocd.local
    path: "/"
    # extraHosts: 
    #   - name: argocd.local.192.168.105.13.nip.io
    #     path: "/(.*)"
    #   - name: 192.168.105.13.nip.io
    #     path: "/(.*)"
    # extraPaths:
    #   - path: "/(.*)"
    #     pathType: Prefix
    #     backend:
    #       service:
    #         name: argo-cd-argocd-server
    #         port:
    #           name: http


oidc:
  oauth:
    encryptedClientSecret: AgBYYyccDyY6uQKwfAOqJew/i1DBXFR7Yd2fevBZaKmr464gnSDDF3AH2pgGWFTLvXqmcctSbqlkmLE/Aklx9pVgR4hetsl8DWx8DGlsfy+1g3fXI0/XcMHC/P0zXzLaH5lHYt9bfonAgw8PcRh7gSgZen43p2wbR2JAU6Tm9I+VH9onrK2XusPQVJTRxTlCDPtJeFl4HybFpfQpocppdCYtrRyMNo2ySs5l/abwWTfR4HUgl+Bzy8ei5ycEeoByFSqKWX2EMlZaPOh+gZe/3t7v/vIWwt/3H9hX+KKENxsula+citRzsLvK4e3i0nj7M4OzyaZVrsnX+WSX6uA7dt1qQtg9vGxzienjNfh5/2aO0MwMrVjd6KLRMJphXf45La2xdcWRGAHRH4cnVAevZchkBiSfvBmJMdDXpk1Gqx4lYsxBdVtLN9Dj6wJunuSGm9G/64US4SHHSrMh3lj29uAIeQ3JsJ3BgJDtd8lD8Qxss0SylBd4JJkRgYnhWQLqNtgCmSXQD/3uyXtTGGZUUvhvaa9oIiP1mg1eyD8odbxFiz12P1zfA7kkFZRWb9/mf/Fb71iyGP8ktlqsRYy2uw8UMxb02S+FihMk1mj/O5mxd/fOKM0kOY05Ipt5ZxbGdixAqTLLPRA90dQTTA2D7jB+JYTaymwCx1B1iqJSiL8Q3dYY969QAT1xkrcpmCL2qq4RqZ+RVp2YY6+LrVWXhoLnH3XIjDo1IIlKxIP2QushRfYATK9pJvAn
    encryptedClientId: AgAmcCT+sh71CFrH7MIlyCAsp4RkVrWRijRGF2ABIKeOPOUBxYjyUPKISdclqB8N7wgLjaL8JFUPcKcpMUVCRvFyUMvGrtBT7lbsycvQ9sfPzLeyCao5Pge62nnv0H2XXnfuEaQxx2U5qlBm12tDOJjeBDbbb2chflmhDNdfmvFviIsMcxmrGCT2vUh3+xOwTQbptdfnB3oM9yhrU4nqv6ft2JA0pji25l1prQ59/rGOUjzNZM7ifo6RR4zIcxMYmOXtUcAE+53NwQ3bHCD0Yv94WxDvJ9KshUNMNhMfoJUtB8BBamEVFChMoYMU8PmAeLJPwvozNtx8i3qmMSExLlDcVkO3DQDqfSfaPvclJTAc0LFAIrVK/AecMOlZGqP8Wap8Bm9IPCntZ5H2oDtrnytNRDlyCm96Gscm0wSIxPcY+aNhRmpJ2mSCWKT1NexSPolE4qih1ykvYVt1f2oVldcdMJ+v+YT1eJA4p5QpDgjjqBUvrFPW7TJxRkKt208X/KZ62/pSclX31/vKLlndHd7YZRut1MesYwOnIeVTQrYZ2MA0BfJvo/TpaMuWOs0HHZZx4ld+T12+/twOWblzlbfPAzQCU7OgYNdm1sVKvHu4vhnRsF3qEcdibWWUZ8bgdCjwTzmJTIJ9xqi19svU0VC/fEehBJdY10f+a98jddxr6mFx3j8m6pKgGTt5Pl/AXok89woQKc+553riCb0Srp6EGk9w4w==