#https://github.com/argoproj/argo-helm/blob/main/charts/argo-cd/values.yaml
dex:
  enabled: false
configs:
  cm:
    create: true
    kustomize.buildOptions: --enable-helm
    resource.exclusions: |
      - apiGroups:
        - "velero.io"
        kinds:
        - "Backup"
        - "Restore"
        clusters:
        - "*"
  params:
    server.insecure: true
    server.rootpath: "/argocd"
    server.basehref: "/argocd"
server:
  ingress:
    enabled: true
    ingressClassName: "nginx"
    https: false
    annotations:
      nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/rewrite-target: /$1
    hostname:
      - argocd.local
    paths:
      - "/(.*)"
    extraHosts: 
      - name: argocd.local.192.168.105.13.nip.io
        path: "/(.*)"
      - name: 192.168.105.13.nip.io
        path: "/(.*)"
    # extraPaths:
    #   - path: "/(.*)"
    #     pathType: Prefix
    #     backend:
    #       service:
    #         name: argo-cd-argocd-server
    #         port:
    #           name: http
