apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# sortOptions:
#   order: fifo

helmGlobals:
  chartHome: helm-charts

helmCharts:
- name: sealed-secrets
  namespace: sealed-secrets
  repo:  https://bitnami-labs.github.io/sealed-secrets
  version: 2.16.1
  releaseName: sealed-secrets
  # valuesFile: values_sealed-secrets.yaml
  includeCRDs: true
  valuesInline:
    fullnameOverride: sealed-secrets
    namespace: sealed-secrets
    commonLabels:
      app: sealed-secrets



resources:
- namespace.yaml


#- overlays/Application_csi.yaml

# patchesStrategicMerge:
# - |-
#   apiVersion: v1
#   kind: ConfigMap
#   metadata:
#     name: argocd-cm
