apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
  finalizers: {}
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: root
  source:
    path: cluster/ns/argocd
    repoURL: "https://github.com/andrey-parkhomets/argotest.git"
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - PrunePropagationPolicy=orphan