apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: managed-clusters-all
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
      repoURL: https://github.com/andrey-parkhomets/argotest.git
      revision: HEAD
      directories:
      - path: cluster/managed-clusters/*
  template:
    metadata:
      name: 'managed-cluster-{{.path.basename}}'
    spec:
      project: "root"
      source:
        repoURL: https://github.com/andrey-parkhomets/argotest.git
        targetRevision: HEAD
        path: '{{.path.path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: argocd
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: true
      ignoreDifferences:
      - kind: ConfigMap
        jqPathExpressions:
        - '.stringData.config'
