apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: sealed-secrets
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: sealed-secrets
  project: default
  source:
    path: charts/sealed-secrets
    repoURL: https://github.com/andrey-parkhomets/argotest.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
