apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: azdo-emberstack
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: azdo-emberstack
  project: default
  source:
    path: charts/azure-pipelines-agent
    repoURL: https://github.com/andrey-parkhomets/argotest.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
