apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kvname
spec:
  provider: azure
  secretObjects:
  - secretName: my-secret
    type: opaque
    data:
    - objectName: DemoSecret
      key: DemoSecret
  parameters:
    usePodIdentity: "false"
    keyvaultName: kv-microk8s-arc
    objects: |
      array:
        - |
          objectName: DemoSecret
          objectAlias: DemoSecret
          objectType: secret
          filePermission: 0755
    tenantId: 580ac1bb-0b92-4429-bd35-bacc4d2b3cbd
