apiVersion: v2
name: azdo-emberstack
version: 1.0.0
dependencies:
  - name: emberstack
    version: 2.2.26
    repository: https://emberstack.github.io/helm-charts
home: https://github.com/emberstack/docker-azure-pipelines-agent

keywords:
  - azdo
  - emberstack
maintainers:
  - email: andrey.parkhomets@gmail.com
    name: parkhomets