apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

# resources:
# - overlays/somegthing_extra.yaml


helmCharts:
- name: argo-cd
  repo: https://argoproj.github.io/argo-helm
  version: 5.51.2
  releaseName: argocd
  namespace: argocd
  valuesFile: values.yaml
