argo-cd:
  dex:
    enabled: false
  configs:
    params:
      server.insecure: true
      server.rootpath: "/argocd"
      server.basehref: "/argocd"

  server:
    ingress:
      enabled: true
      ingressClassName: "nginx"
      https: false
      annotations:
        nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
        nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
        nginx.ingress.kubernetes.io/rewrite-target: /$1
      hosts:
        - argocd.local
      paths:
        - "/(.*)"
      # extraPaths:
      #   - path: "/(.*)"
      #     pathType: Prefix
      #     backend:
      #       service:
      #         name: argo-cd-argocd-server
      #         port:
      #           name: http
