apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: appset-core-dev
spec:
  generators:
    - matrix:
        generators:
          - clusters:
              selector:
                matchExpressions:
                - key: env
                  operator: In
                  values:
                  - dev
                # - key: color
                #   operator: In
                #   values:
                #   - green
          - list:
              elements:
              - appName: external-secrets
                namespace: kube-infra-vault
  strategy:
    type: RollingSync
    rollingSync:
      steps:
        - matchExpressions:
            - key: appName
              operator: In
              values:
                - external-secrets
                # - ingress-nginx
        # - matchExpressions:
        #     - key: appName
        #       operator: In
        #       values:
        #         - cluster-autoscaler
        #         - kubernetes-dashboard
  goTemplate: true
  template:
    metadata:
      name: '{{.appName}}-{{.metadata.labels.env}}-{{.metadata.labels.color}}'
      labels:
        appName: '{{.appName}}'
        site: '{{.metadata.labels.site}}'
        env: '{{.metadata.labels.env}}'
        color: '{{.metadata.labels.color}}'
      annotations:
        team: '{{.metadata.annotations.team}}' # Use team annotation
    spec:
      project: project-dev
      source:
        repoURL: https://github.com/andrey-parkhomets/argotest.git
        targetRevision: HEAD
        path: "cluster/managed-k8s-charts/{{.appName}}"
        helm:
          releaseName: '{{.appName}}'
          valueFiles:
            - "values.yaml"
            # - "values-{{.metadata.labels.env}}.yaml"
            # - "../../{{.appName}}/values-{{.metadata.labels.env}}-{{.metadata.labels.label}}.yaml"
      destination:
        name: '{{.name}}'
        namespace: '{{.namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: true
        syncOptions:
        - Retry=true
        - ApplyOutOfSyncOnly=true
        - FailOnSharedResource=true
        - PrunePropagationPolicy=orphan
        retry:
          limit: 5 # Maximum number of retries
          backoff:
            duration: 5s # Initial retry interval
            factor: 2 # Multiplication factor for the backoff
            maxDuration: 1m # Maximum retry interval