apiVersion: v1
kind: Secret
metadata:
  name: dev-cluster1
  labels:
    argocd.argoproj.io/secret-type: cluster
    env: dev
type: Opaque
stringData:
  name: dev-cluster1  # Human-readable name for the cluster
  server: https://dev-cluster1.apik8s.example.com  # API server URL for in-cluster