apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: project-dev-clusters
  namespace: argocd
spec:
  description: Project for DEV clusters
  sourceRepos:
  - '*'

  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: '*'
    name: 'dev-0001'
  - namespace: '*'
    name: 'dev-0002'
  orphanedResources:
    warn: true
  permitOnlyProjectScopedClusters: true
