apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: project-dev-clusters
  namespace: argocd
spec:
  sourceRepos:
  - '*'
  destinations:
  - namespace: '*'
    server: '*'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
# spec:
#   description: Project for DEV clusters
#   sourceRepos:
#   - '*'

#   clusterResourceWhitelist:
#   - group: '*'
#     kind: '*'
#   destinations:
#   - namespace: '*'
#     name: '*'
#   orphanedResources:
#     warn: true
#   permitOnlyProjectScopedClusters: true
