apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: project-dev
  namespace: argocd
spec:
  description: Project for DEV clusters
  sourceRepos:
  - '*'

  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: '*'
    name: '*'
  orphanedResources:
    warn: true
  permitOnlyProjectScopedClusters: true