nameReference:
- kind: Secret
  version: v1
  fieldSpecs:
  - kind: SealedSecret
    path: metadata/name
  - kind: SealedSecret
    path: spec/template/metadata/name
  - kind: StatefulSet
    path: spec/template/spec/containers/env/name/valueFrom/secretKeyRef/name