apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./azure-pipelines-agent/templates/serviceaccount.yaml
  - ./azure-pipelines-agent/templates/statefulset.yaml
  - ./sealed-secret.yaml