apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# namespace is important to set for configuration/sealed-secret-config.yaml to work properly
namespace: azdo-emberstack

resources:
  - ./sealed-secret.yaml
  - ./azure-pipelines-agent/templates/serviceaccount.yaml
  - ./azure-pipelines-agent/templates/statefulset.yaml


# secretGenerator:
#   - name: my-secret
#     type: Opaque
# configurations:
#   - configuration/sealed-secret-config.yaml
generatorOptions:
  ##### in worth case just disable hash
  # disableNameSuffixHash: true
  annotations:
    sealedsecrets.bitnami.com/managed: "true"
    sealedsecrets.bitnami.com/namespace-wide: "true"