kind: Kustomization
sortOptions:
  order: legacy
  legacySortOptions:
    orderFirst:
    - Namespace
    - ResourceQuota
    - StorageClass
    - CustomResourceDefinition
    - ServiceAccount
    - PodSecurityPolicy
    - Role
    - ClusterRole
    - RoleBinding
    - ClusterRoleBinding
    - ConfigMap
    - Secret
    - Endpoints
    - Service
    - LimitRange
    - PriorityClass
    - PersistentVolume
    - PersistentVolumeClaim
    - Deployment
    - StatefulSet
    - CronJob
    - PodDisruptionBudget
    orderLast:
    - MutatingWebhookConfiguration
    - ValidatingWebhookConfiguration
    - SealedSecret

# namespace is important to set for configuration/sealed-secret-config.yaml to work properly
namespace: azdo-emberstack



generatorOptions:
  labels: # adds labels to the generated resources
    my.label: mylabel
  disableNameSuffixHash: true # disables the suffix generation
  immutable: true # marks the resources as immutable
  annotations:
    sealedsecrets.bitnami.com/managed: "true"
    sealedsecrets.bitnami.com/namespace-wide: "true"

secretGenerator:
  - name: my-secret
    type: Opaque
configurations:
  - configuration/sealed-secret-config.yaml

resources:
  - ./sealed-secret.yaml
  - ./azure-pipelines-agent/templates/serviceaccount.yaml
  - ./azure-pipelines-agent/templates/statefulset.yaml

