---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: my-secret
  namespace: azdo-emberstack
spec:
  encryptedData:
    my-key: AgAFTqwXkbfQGSBU9HYcf4RxnPtatA/qcHAHpnjfOC6lkZ+ZoQqFzYWdVpdcG0lqQGnbGWWfyqrhKU34F+1KLWROhlSczDR1uW3WI41QkPALREgxiUbUyeaCWMb6zm8xZJI9uruvrIK8NwxwuOwkXbBN0kS5CbOvGDpKvk68c+AXrDXixXYYi0XArrzxqFOqKFp7R/K+TNU91RTaXROL9nfkixIrNoKNMAQP/5Wlo3SvyKlHaU0ovxRXVuTxX2w/UMarlTHXsjYsqd7sv6RS1BfOuZ/eJUDHepOANw7qe7v8CHp/0h3jo+i+mYQWIToI+s+8T4WbRrV1gl89I8y3OiBwTSjfUKZ5iS2N8u2o1G0sQqowQz5zDERiQa9bZ7YxtqL/R+oA0507b7p0pOchqlD/TC51uTrcxrCx/4Wre7mNdBupvkBrfSyUhBP8+qqp6ae1izUQjVsaNf8Iw3jGjLmuk/7OXQ69JR1CI4g5NUW1DY6l8DBs8NplSXJbD9zN4N0971/Q+izZU6tL/ym4iA6vDRgDOPk5DWRp/tavrQUeu87gPISoxcpSV4J/do/1uCXJo7gvHtQVoTILMImE2xFO75r2BpzPyqY7mzZjhuVOWO+3INFnyLZ9DbcfghY3V7VxLdRbqXVYUa8maKUneYKWupmydRaFYy2hySuj+SJJHH1i4aFGwTa9GwpLuuc2YndX2mytuoAaXkHQJr9lbNbEXBkcZiAClLibGqabC6cJp5XGKhS6I797FnYTOmPhIz2Y3xxK
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: my-secret
      namespace: azdo-emberstack
