apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: core-apps
spec:
  generators:
    - matrix:
        generators:
          - clusters:
              selector:
                matchExpressions:
                - key: env
                  operator: In
                  values:
                  - dev
                  # - prod

          - list:
              elements:
              - appName: external-secrets
                namespace: kube-infra-vault
  strategy:
    type: RollingSync
    rollingSync:
      steps:
        - matchExpressions:
            - key: appName
              operator: In
              values:
                - external-secrets
                # - ingress-nginx
        # - matchExpressions:
        #     - key: appName
        #       operator: In
        #       values:
        #         - cluster-autoscaler
        #         - kubernetes-dashboard
  goTemplate: true
  template:
    metadata:
      name: '{{.name}}-{{.appName}}'
      labels:
        appName: '{{.appName}}'
        site: '{{.metadata.labels.site}}' # Use cluster site label
        env: '{{.metadata.labels.env}}' # Use environment label
      # annotations:
      #   managedBy: '{{.metadata.annotations.team}}' # Use team annotation
    spec:
      project: root
      source:
        repoURL: https://github.com/andrey-parkhomets/argotest.git
        targetRevision: HEAD
        path: "cluster/managed-k8s-charts/{{.appName}}"
        helm:
          releaseName: '{{.appName}}'
          valueFiles:
            - "values.yaml"
            # - "values-{{.metadata.labels.env}}.yaml"
            # - "../../{{.appName}}/values-{{.metadata.labels.env}}-{{.metadata.labels.label}}.yaml"
      destination:
        server: '{{.name}}'
        namespace: '{{.namespace}}'
      syncPolicy:
        automated: {}