---
csi-secrets-store-provider-azure:
  enableArcExtension: false
  # linux:
  #   kubeletRootDir: /var/snap/microk8s/common/var/lib/kubelet
  secrets-store-csi-driver:
    linux:
      #microk8s only !
      kubeletRootDir: /var/snap/microk8s/common/var/lib/kubelet